// ABOUTME: gRPC service definition for dynamic DNS record management.
// ABOUTME: Defines List, Upsert, and Delete RPCs with Record message type.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/dynupdate.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Ttl           uint32                 `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Priority      uint32                 `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Weight        uint32                 `protobuf:"varint,6,opt,name=weight,proto3" json:"weight,omitempty"`
	Port          uint32                 `protobuf:"varint,7,opt,name=port,proto3" json:"port,omitempty"`
	Flag          uint32                 `protobuf:"varint,8,opt,name=flag,proto3" json:"flag,omitempty"`
	Tag           string                 `protobuf:"bytes,9,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_proto_dynupdate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynupdate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_proto_dynupdate_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Record) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Record) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *Record) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Record) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Record) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Record) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Record) GetFlag() uint32 {
	if x != nil {
		return x.Flag
	}
	return 0
}

func (x *Record) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_dynupdate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynupdate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_dynupdate_proto_rawDescGZIP(), []int{1}
}

func (x *ListRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_dynupdate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynupdate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_dynupdate_proto_rawDescGZIP(), []int{2}
}

func (x *ListResponse) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type UpsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *Record                `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertRequest) Reset() {
	*x = UpsertRequest{}
	mi := &file_proto_dynupdate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertRequest) ProtoMessage() {}

func (x *UpsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynupdate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertRequest.ProtoReflect.Descriptor instead.
func (*UpsertRequest) Descriptor() ([]byte, []int) {
	return file_proto_dynupdate_proto_rawDescGZIP(), []int{3}
}

func (x *UpsertRequest) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

type UpsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *Record                `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertResponse) Reset() {
	*x = UpsertResponse{}
	mi := &file_proto_dynupdate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertResponse) ProtoMessage() {}

func (x *UpsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynupdate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertResponse.ProtoReflect.Descriptor instead.
func (*UpsertResponse) Descriptor() ([]byte, []int) {
	return file_proto_dynupdate_proto_rawDescGZIP(), []int{4}
}

func (x *UpsertResponse) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_dynupdate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynupdate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_dynupdate_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DeleteRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_dynupdate_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dynupdate_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_dynupdate_proto_rawDescGZIP(), []int{6}
}

var File_proto_dynupdate_proto protoreflect.FileDescriptor

const file_proto_dynupdate_proto_rawDesc = "" +
	"\n" +
	"\x15proto/dynupdate.proto\x12\fdynupdate.v1\"\xc6\x01\n" +
	"\x06Record\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\rR\x03ttl\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\rR\bpriority\x12\x16\n" +
	"\x06weight\x18\x06 \x01(\rR\x06weight\x12\x12\n" +
	"\x04port\x18\a \x01(\rR\x04port\x12\x12\n" +
	"\x04flag\x18\b \x01(\rR\x04flag\x12\x10\n" +
	"\x03tag\x18\t \x01(\tR\x03tag\"!\n" +
	"\vListRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\">\n" +
	"\fListResponse\x12.\n" +
	"\arecords\x18\x01 \x03(\v2\x14.dynupdate.v1.RecordR\arecords\"=\n" +
	"\rUpsertRequest\x12,\n" +
	"\x06record\x18\x01 \x01(\v2\x14.dynupdate.v1.RecordR\x06record\">\n" +
	"\x0eUpsertResponse\x12,\n" +
	"\x06record\x18\x01 \x01(\v2\x14.dynupdate.v1.RecordR\x06record\"M\n" +
	"\rDeleteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\x10\n" +
	"\x0eDeleteResponse2\xdb\x01\n" +
	"\x10DynUpdateService\x12=\n" +
	"\x04List\x12\x19.dynupdate.v1.ListRequest\x1a\x1a.dynupdate.v1.ListResponse\x12C\n" +
	"\x06Upsert\x12\x1b.dynupdate.v1.UpsertRequest\x1a\x1c.dynupdate.v1.UpsertResponse\x12C\n" +
	"\x06Delete\x12\x1b.dynupdate.v1.DeleteRequest\x1a\x1c.dynupdate.v1.DeleteResponseB4Z2github.com/mauromedda/coredns-updater-plugin/protob\x06proto3"

var (
	file_proto_dynupdate_proto_rawDescOnce sync.Once
	file_proto_dynupdate_proto_rawDescData []byte
)

func file_proto_dynupdate_proto_rawDescGZIP() []byte {
	file_proto_dynupdate_proto_rawDescOnce.Do(func() {
		file_proto_dynupdate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dynupdate_proto_rawDesc), len(file_proto_dynupdate_proto_rawDesc)))
	})
	return file_proto_dynupdate_proto_rawDescData
}

var file_proto_dynupdate_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_dynupdate_proto_goTypes = []any{
	(*Record)(nil),         // 0: dynupdate.v1.Record
	(*ListRequest)(nil),    // 1: dynupdate.v1.ListRequest
	(*ListResponse)(nil),   // 2: dynupdate.v1.ListResponse
	(*UpsertRequest)(nil),  // 3: dynupdate.v1.UpsertRequest
	(*UpsertResponse)(nil), // 4: dynupdate.v1.UpsertResponse
	(*DeleteRequest)(nil),  // 5: dynupdate.v1.DeleteRequest
	(*DeleteResponse)(nil), // 6: dynupdate.v1.DeleteResponse
}
var file_proto_dynupdate_proto_depIdxs = []int32{
	0, // 0: dynupdate.v1.ListResponse.records:type_name -> dynupdate.v1.Record
	0, // 1: dynupdate.v1.UpsertRequest.record:type_name -> dynupdate.v1.Record
	0, // 2: dynupdate.v1.UpsertResponse.record:type_name -> dynupdate.v1.Record
	1, // 3: dynupdate.v1.DynUpdateService.List:input_type -> dynupdate.v1.ListRequest
	3, // 4: dynupdate.v1.DynUpdateService.Upsert:input_type -> dynupdate.v1.UpsertRequest
	5, // 5: dynupdate.v1.DynUpdateService.Delete:input_type -> dynupdate.v1.DeleteRequest
	2, // 6: dynupdate.v1.DynUpdateService.List:output_type -> dynupdate.v1.ListResponse
	4, // 7: dynupdate.v1.DynUpdateService.Upsert:output_type -> dynupdate.v1.UpsertResponse
	6, // 8: dynupdate.v1.DynUpdateService.Delete:output_type -> dynupdate.v1.DeleteResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_dynupdate_proto_init() }
func file_proto_dynupdate_proto_init() {
	if File_proto_dynupdate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dynupdate_proto_rawDesc), len(file_proto_dynupdate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dynupdate_proto_goTypes,
		DependencyIndexes: file_proto_dynupdate_proto_depIdxs,
		MessageInfos:      file_proto_dynupdate_proto_msgTypes,
	}.Build()
	File_proto_dynupdate_proto = out.File
	file_proto_dynupdate_proto_goTypes = nil
	file_proto_dynupdate_proto_depIdxs = nil
}
